version: '3.5'

networks:
  maddynyan_network:

services:
  db:
    container_name: maddynyan_postgres_db
    image: postgres:12
    restart: always
    networks:
      - maddynyan_network
    ports:
      - "${DB_PORT}:5432"
    environment:
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
  daphne:
    build: .
    container_name: maddynyan_daphne
    restart: always
    command: bash -c "python3 manage.py migrate && python3 manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p ${DAPHNE_PORT} maddynyan_server.asgi:application"
    environment:
      DB_PORT: ${DB_PORT}
      DB_HOST: db
      MACHINE_HOST: 127.0.0.1
      HOST_IP: ${HOST_IP}
      HOST_PORT: ${DAPHNE_PORT}
      NGINX_PORT: ${NGINX_PORT}
      HOST_DOMAIN: ${HOST_DOMAIN}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:${DAPHNE_PORT}:${DAPHNE_PORT}"
    networks:
      - maddynyan_network
    depends_on:
      - db
    volumes:
      - ./files:/code/files
