# Generated by Django 3.0.3 on 2020-02-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramStatisticsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Инстаграм',
                'verbose_name_plural': 'Инстаграм',
            },
        ),
        migrations.CreateModel(
            name='TwitchStatisticsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Твич',
                'verbose_name_plural': 'Твич',
            },
        ),
    ]
