# Generated by Django 3.0.5 on 2020-05-07 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 7, 17, 33, 38, 132648, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotemodel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
